# Generated by Django 3.2.11 on 2022-01-20 19:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='text',
            field=wagtail.core.fields.StreamField([('text_fill', wagtail.core.blocks.RichTextBlock())], default=None),
        ),
    ]
