# Generated by Django 3.2.11 on 2022-01-20 19:32

from django.db import migrations, models
import django.db.models.deletion
import polls.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220119_0849'),
        ('blog', '0004_alter_blogpage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='text',
            field=wagtail.core.fields.StreamField([('text_fill', wagtail.core.blocks.RichTextBlock()), ('polls', wagtail.core.blocks.StructBlock([('poll', wagtail.snippets.blocks.SnippetChooserBlock(polls.models.Question))]))], default=None),
        ),
    ]
